# Generated by Django 4.0.6 on 2022-07-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, upload_to='photos/%Y-%m-%d'),
        ),
    ]
