# Generated by Django 4.0.6 on 2022-07-24 20:13

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0003_alter_foto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='titulo',
        ),
        migrations.AddField(
            model_name='foto',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), default=list, size=None),
        ),
        migrations.AddField(
            model_name='foto',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='foto',
            name='photo',
            field=models.ImageField(default='defaultUser.jpg', upload_to='photos/%Y-%m-%d'),
        ),
        migrations.AddField(
            model_name='foto',
            name='profile',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foto',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
