# Generated by Django 4.0.6 on 2022-07-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_remove_foto_foto_remove_foto_titulo_foto_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='photo',
            field=models.ImageField(default='defaultPhoto.jpg', upload_to='photos/%Y-%m-%d'),
        ),
    ]
