# Generated by Django 4.0.6 on 2022-07-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='publishData',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
