# Generated by Django 4.0.6 on 2022-07-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0008_remove_foto_public_foto_private_alter_foto_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='publishData',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
