# Generated by Django 4.0.6 on 2022-07-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0010_remove_foto_comments_foto_likes_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(related_name='saved_post', to='album.foto'),
        ),
    ]
