# Generated by Django 4.0.6 on 2022-07-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0014_alter_foto_profile_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='', max_length=255),
        ),
    ]
