# Generated by Django 4.0.6 on 2022-07-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0015_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(default='', max_length=255),
        ),
    ]
