# Generated by Django 4.0.6 on 2022-08-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0019_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dataTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
